services:
  app:
    build: .
    container_name: policy-api-app
    hostname: policy-api
    ports:
      - 3000:3000
    networks:
      - policy-base_default
    volumes:
      - .:/opt/app
      - rubygems:/usr/local/bundle
    command: bash -c 'bundle exec rails s -b 0.0.0.0'
networks:
  policy-base_default:
    external: true
volumes:
  rubygems:
