services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development
    networks:
      - policy-base_default
    volumes:
      - .:/opt/app
      - rubygems:/usr/local/bundle
networks:
  policy-base_default:
    external: true
volumes:
  rubygems:
